server:
  port: 10088
spring:
  datasource:
    url: jdbc:mysql://106.54.68.249:3326/test_db?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: Zz960518.
    username: remote
    driver-class-name: com.mysql.cj.jdbc.Driver
scheduling:
  enable: true
logging:
  file:
    name: /home/com/log/myLog.log