server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://106.54.68.249:3326/test_db?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: movie@159357
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
